services:
  ebs:
    build: ebs
    restart: unless-stopped
    ports:
      - 80:3000
    depends_on:
      - db
      - logger
    environment:
      MYSQL_HOST: db
      MYSQL_USER: ebs
      MYSQL_PASSWORD: ebs
      MYSQL_DATABASE: ebs
      LOGGER_HOST: logger

  logger:
    build: logger
    restart: unless-stopped
    ports:
      - 81:3000
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: ebs
      MYSQL_PASSWORD: ebs
      MYSQL_DATABASE: ebs

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: ebs
      MYSQL_USER: ebs
      MYSQL_PASSWORD: ebs
    volumes:
      - ./_volumes/db:/var/lib/mysql
