services:
  ebs:
    build: ebs
    restart: unless-stopped
    ports:
      - 80:3000
    depends_on:
      - db
      - logger
    environment:
      DB_HOST: db
      DB_USER: ebs
      DB_PASSWORD: ebs
      DB_NAME: ebs
      LOGGER_HOST: logger
      LOGGER_PORT: 81

  logger:
    build: logger
    restart: unless-stopped
    ports:
      - 81:3000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ebs
      DB_PASSWORD: ebs
      DB_NAME: ebs

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ebs
      MYSQL_USER: ebs
      MYSQL_PASSWORD: ebs
    volumes:
      - ./_volumes/db:/var/lib/mysql
