services:
  ebs:
    build: ebs
    restart: unless-stopped
    ports:
      - 80:3000
    depends_on:
      - db
      - logger
    environment:
      MYSQL_HOST: db
      MYSQL_USER: ebs
      MYSQL_DATABASE: ebs
      LOGGER_HOST: logger
    env_file:
      - ./.docker.env

  logger:
    build: logger
    restart: unless-stopped
    ports:
      - 81:3000
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: ebs
      MYSQL_DATABASE: ebs
    env_file:
      - ./.docker.env

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: ebs
      MYSQL_USER: ebs
    env_file:
      - ./.docker.env
    volumes:
      - ./_volumes/db:/var/lib/mysql
